FROM node:18-alpine3.15

WORKDIR /usr/src/app

COPY package.json ./

COPY tsconfig.json ./

RUN npm install

COPY ./ ./

RUN npx prisma generate --schema ./prisma/schema.prisma

RUN npm run build


EXPOSE 4000
EXPOSE 5555

CMD [ "npm", "start" ]